### ISSUE TITLE
’ ./waf ‘ error

### ISSUE THREAD

**Issue by Luoser2020** [JimmyLi-Network/NS3-implementation-MPTCP-Multiple-Path-TCP#1]
Hello, for your code I have an error when running, the following is the prompt message ：

invalid lock file in /root/NS3-implementation-MPTCP-Multiple-Path-TCP
Waf: The wscript in '/root/NS3-implementation-MPTCP-Multiple-Path-TCP' is unreadable
Traceback (most recent call last):
  File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Scripting.py", line 85, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Scripting.py", line 109, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/extras/compat15.py", line 88, in load_module
    ret=rev(path)
  File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Context.py", line 269, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/wscript", line 65, in <module>
    VERSION = file("VERSION", "rt").read().strip()
IOError: [Errno 2] No such file or directory: 'VERSION'

**Comment by ucandobetter** [comment]
> Hello, for your code I have an error when running, the following is the prompt message ：
> 
> invalid lock file in /root/NS3-implementation-MPTCP-Multiple-Path-TCP Waf: The wscript in '/root/NS3-implementation-MPTCP-Multiple-Path-TCP' is unreadable Traceback (most recent call last): File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Scripting.py", line 85, in waf_entry_point set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE) File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Scripting.py", line 109, in set_main_module Context.g_module=Context.load_module(file_path) File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/extras/compat15.py", line 88, in load_module ret=rev(path) File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Context.py", line 269, in load_module exec(compile(code,path,'exec'),module.**dict**) File "/root/NS3-implementation-MPTCP-Multiple-Path-TCP/wscript", line 65, in VERSION = file("VERSION", "rt").read().strip() IOError: [Errno 2] No such file or directory: 'VERSION'

Hello，myfriend, I have encountered the same problem, have you solved it? In addition, I would like to ask you how to implement mptcp on ns3, I have used the code of Kashif-Nadeem/ns-3-mptcp, but I do not know how to write an mptcp instance, I would be very grateful if you can help me, thank you
